# Lab 5 part 3
# Joseph Godlewski, Zhiting Zhu

all: auplay synth song

auplay:
	make -f auplay.mk

synth: 
	make -f synth.mk

song:
	make -f song.mk

clean:
	make -f auplay.mk clean
	make -f synth.mk clean
	make -f song.mk clean
